server:
  port: 8080
  error:
    include-stacktrace: never
springdoc:
  api-docs:
    enabled: true
spring:
  application:
    name: eshop


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.130:3306/eshop_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

logging:
  level:
    root: info
    com.kelvin: info


