# 因为不使用 Spring Boot 内置的应用服务所以这里并不需要指定 server.port
#server:
#  port: 8081
spring:
  application:
    name: goods-service
  main:
    allow-bean-definition-overriding: true #支持名称相同的bean的覆盖,默认true
  cloud:
    nacos:
      server-addr: 192.168.3.22:8848 # Nacos地址
      username: nacos
      password: nacos

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.130:3306/eshop_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true


#dubbo配置 dubbo.protocols：配置两种协议，其中rest协议定义 8080 端口并使用 netty 作为应用服务器
dubbo:
  scan:
    base-packages: org.kelvin.eshopbackend.goods.service.impl
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 8080
      server: netty
  registry:
    address: spring-cloud://localhost
  consumer:
    timeout: 5000
    check: false
    retries: 0
  cloud:
    subscribed-services:


logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
