
#dubbo配置 dubbo.protocols：配置两种协议，其中rest协议定义 8080 端口并使用 netty 作为应用服务器
dubbo:
  scan:
    base-packages: com.kelvin.eshop.goods.service.impl
  protocol:
      name: dubbo
      port: -1
  consumer:
    timeout: 5000
    check: false
    retries: 0
  cloud:
    subscribed-services:


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: INFO
