server:
  port: 8082
  error:
    include-stacktrace: never
springdoc:
    api-docs:
      enabled: true
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.3.22:8848 # Nacos地址

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.130:3306/eshop_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG
