#server:
#  port: 8082
#  error:
#    include-stacktrace: never
springdoc:
    api-docs:
      enabled: true
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.22:8848 # Nacos地址

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.22:3306/eshop_db_order?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    mapping-resources:
      - orm/order.xml



logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: INFO

dubbo:
  scan:
    base-packages: com.kelvin.eshop.order.service.impl
  protocol:
    name: dubbo
    port: -1
  consumer:
    timeout: 5000
    check: false
    retries: 0
